name: "Lint"

on:
  workflow_call:

jobs:
  lint:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4"

        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"

        - name: "Install requirements"
          run: python3 -m pip install ruff

        - name: "Run"
          run: python3 -m ruff check .
